# toml draft

[glyphs]

# any glyphs on the physical sheet. maximum of one name per glyph. multiple ligatures are maybe fine?
sheet = [
  # row 0
  {codepoint = 0xf1900, name = "aTok",      ligature = "a"          },
  # assume that every left- or right-facing glyph is mirrored
  {codepoint = 0xf1901, name = "akesiTok",  ligature = "a k e s i"  , rotate = true, direction = "up"},
  {codepoint = 0xf1902, name = "alaTok",    ligature = "a l a"      },

  # row 6
  {codepoint = 0xf1990, stackable = false, name = "cartoucheStartTok", ligature = "bracketleft",  cartoucheable = false, scan-shift = "right"},
  {codepoint = 0xf1991, stackable = false, name = "cartoucheEndTok",   ligature = "bracketright", cartoucheable = false, scan-shift = "left"},
  {codepoint = 0xf199c, stackable = false, name = "middotTok",         ligature = "period"},
  {codepoint = 0xf199d, stackable = false, name = "colonTok",          ligature = "colon"},
  {codepoint = 0x69,    stackable = false, name = "i"},
]

generated = [
  {codepoint = 0, name = "cartoucheMiddleTok", ligature = "equals", type = "middle", source-glyph-index = 121 }
]

[settings]

# UCSUR codepoints for words not included in the default sheet, since people may write them in
unused_ucsur_words = [
  {codepoint = 0, name = "apejaTok", ligature = "a p e j a"},
  {codepoint = 0, name = "pakeTok",  ligature = "p a k e"},
  {codepoint = 0, name = "poweTok",  ligature = "p o w e"},
]

synonyms = [
  {ligature = "a l i",       target-name = "aleTok"    },
  {ligature = "l i n u w i", target-name = "linluwiTok"},
  {ligature = "k e p e n",   target-name = "kepekenTok"},
]

# the following glyph names are prerequisites for custom ligatures. for example, the ligature "a l e" has "a", "l", "e" as prerequisites.
# it would be cool if they appear correctly, but if an architecture change requires it, it's fine if they appear as blank spaces.
prerequisite_glyphs = [
  # letters
  {codepoint = 0x61, name = "a", target-name = "aTok"},
  {codepoint = 0x65, name = "e", target-name = "eTok"},
  {codepoint = 0x6e, name = "n", target-name = "nTok"},
  {codepoint = 0x6f, name = "o", target-name = "oTok"},
    
  {codepoint = 0x41, name = "A", target-name = "aTok"},
  {codepoint = 0x45, name = "E", target-name = "eTok"},
  {codepoint = 0x4e, name = "N", target-name = "nTok"},
  {codepoint = 0x4f, name = "O", target-name = "oTok"},

  {codepoint = 0x49, name = "I", target-name = "i"},
  {codepoint = 0x4a, name = "J", target-name = "j"},
  {codepoint = 0x4b, name = "K", target-name = "k"},
  {codepoint = 0x4c, name = "L", target-name = "l"},
  {codepoint = 0x4d, name = "M", target-name = "m"},
  {codepoint = 0x50, name = "P", target-name = "p"},
  {codepoint = 0x53, name = "S", target-name = "s"},
  {codepoint = 0x54, name = "T", target-name = "t"},
  {codepoint = 0x55, name = "U", target-name = "u"},
  {codepoint = 0x57, name = "W", target-name = "w"},

  {codepoint = 0x62, name = "b", target-name = "p"},
  {codepoint = 0x42, name = "B", target-name = "p"},
  {codepoint = 0x63, name = "c", target-name = "s"},
  {codepoint = 0x43, name = "C", target-name = "s"},
  {codepoint = 0x64, name = "d", target-name = "t"},
  {codepoint = 0x44, name = "D", target-name = "t"},
  {codepoint = 0x66, name = "f", target-name = "p"},
  {codepoint = 0x46, name = "F", target-name = "p"},
  {codepoint = 0x67, name = "g", target-name = "k"},
  {codepoint = 0x47, name = "G", target-name = "k"},
  {codepoint = 0x68, name = "h", target-name = "k"},
  {codepoint = 0x48, name = "H", target-name = "k"},
  {codepoint = 0x71, name = "q", target-name = "k"},
  {codepoint = 0x51, name = "Q", target-name = "k"},
  {codepoint = 0x72, name = "r", target-name = "w"},
  {codepoint = 0x52, name = "R", target-name = "w"},
  {codepoint = 0x76, name = "v", target-name = "w"},
  {codepoint = 0x56, name = "V", target-name = "w"},
  {codepoint = 0x78, name = "x", target-name = "s"},
  {codepoint = 0x58, name = "X", target-name = "s"},
  {codepoint = 0x79, name = "y", target-name = "j"},
  {codepoint = 0x59, name = "Y", target-name = "j"},
  {codepoint = 0x7a, name = "z", target-name = "s"},
  {codepoint = 0x5a, name = "Z", target-name = "s"},

  # numbers (svgtottf_ffpython.py#L422-L424)

  # glyphs for punctuation used in sitelen Lasina prose, such as `,;!?` (svgtottf_ffpython.py#L440-L448)

  # glyphs for ligatures used in unsupported SP features, such as `(){}*",+&` (svgtottf_ffpython.py#L432-438)
]