# toml draft

[glyphs]

# any glyphs on the physical sheet. maximum of one name per glyph. multiple ligatures are maybe fine?

# i need to store both the glyph name, and the index (position) on the physical sheet.
# right now, index is stored implicitly, because this is a TOML array.
# i could turn it into a table, and add an "index" field. this would let me *actually use* TOML's syntax for defining glyphs.
# TOML syntax is helpful for confusing cases, like generating the middle of a cartouche.

sheet = [
  # row 0
  {codepoint = 0xf1900, name = "aTok",      ligature = "a"          },
  # assume that every left- or right-facing glyph is mirrored
  {codepoint = 0xf1901, name = "akesiTok",  ligature = "a k e s i"  , rotate = true, direction = "up"},
  {codepoint = 0xf1902, name = "alaTok",    ligature = "a l a"      },

  # row 6
  {codepoint = 0xf1990, name = "cartoucheStartTok", ligature = "bracketleft",  center = false, scan-shift = "right"},
  {codepoint = 0xf1991, name = "cartoucheEndTok",   ligature = "bracketright", center = false, scan-shift = "left"},
  {codepoint = 0xf199c, name = "middotTok",         ligature = "period"},
  {codepoint = 0xf199d, name = "colonTok",          ligature = "colon"},
  {codepoint = 0x69,    name = "i"},
]

synonyms = [
  {ligature = "a l i",       target-name = "aleTok"    },
  {ligature = "l i n u w i", target-name = "linluwiTok"},
  {ligature = "k e p e n",   target-name = "kepekenTok"},
]

spaces = [
  # support default ASCII ligatures
  {codepoint = 0x7c, width = 1000, name = "pipe"},
  {codepoint = 0x20, width =    0, name = "space"},
  {codepoint = 0x2d, width =    0, name = "hyphen"},

  {codepoint = 0x30, width =    0, name = "zero"},
  {codepoint = 0x31, width =    0, name = "one"},
  {codepoint = 0x32, width =    0, name = "two"},
  {codepoint = 0x33, width =    0, name = "three"},
  {codepoint = 0x34, width =    0, name = "four"},
  {codepoint = 0x35, width =    0, name = "five"},
  {codepoint = 0x36, width =    0, name = "six"},
  {codepoint = 0x37, width =    0, name = "seven"},
  {codepoint = 0x38, width =    0, name = "eight"},
  {codepoint = 0x39, width =    0, name = "nine"},

  # todo: replace these three, and `v`, with rotated lili. it would be cute i think
  {codepoint = 0x5e, width = 1000, name = "north"},
  {codepoint = 0x3c, width = 1000, name = "west"},
  {codepoint = 0x3e, width = 1000, name = "east"},
  # (we treat "v" as a regular letter, instead of calling it "south")

  # fallback for unsupported SP features
  {codepoint = 0x2b, width =    0, name = "plus"},
  {codepoint = 0x26, width =    0, name = "ampersand"},
  {codepoint = 0x7b, width =    0, name = "opencurly"},
  {codepoint = 0x7d, width =    0, name = "closecurly"},
  {codepoint = 0x28, width =    0, name = "openparen"},
  {codepoint = 0x29, width =    0, name = "closeparen"},
  {codepoint = 0x2a, width = 1000, name = "asterisk"},
  {codepoint = 0x22, width = 1000, name = "doublequote"},
  {codepoint = 0x2c, width = 1000, name = "comma"},
  {codepoint = 0x27, width = 1000, name = "singlequote"},

  # fallback for text intended as sitelen Lasina
  {codepoint = 0x21, width = 1000, name = "exclamation"},
  {codepoint = 0x3f, width = 1000, name = "question"},
  {codepoint = 0x3b, width = 1000, name = "semicolon"},

  # UCSUR features
  {codepoint = 0x3000,  width = 1000, name = "ideographicspace"},
  {codepoint = 0x200b,  width =    0, name = "zerowidth"}, # zero-width space
  {codepoint = 0xf1995, width =    0, name = "stackJoinTok"},

  # fallback for unsupported UCSUR features
  {codepoint = 0xf1996, width =    0, name = "nestJoinTok"},
  {codepoint = 0x200d,  width =    0, name = "zerowidthjoiner"},
  {codepoint = 0xf1997, width =    0}, # SP START OF LONG GLYPH
  {codepoint = 0xf1998, width =    0}, # SP END OF LONG GLYPH
  {codepoint = 0xf1999, width =    0}, # SP COMBINING LONG GLYPH EXTENSION
  {codepoint = 0xf199a, width =    0}, # SP START OF REVERSE LONG GLYPH
  {codepoint = 0xf199b, width =    0}, # SP END OF REVERSE LONG GLYPH
]

[[glyphs.generated]]
name      = "cartoucheMiddleTok"
codepoint = 0
ligature  = "equals"
type      = "middle"
start-chaining-at       = "cartoucheStartTok"
end-chaining-at         = "cartoucheEndTok"
derive-glyph-from-index = 121 # cartoucheStartTok
invisible-variant-name  = "invisibleCartoucheMiddleTok"

[[glyphs.generated]]
name      = "longPiMiddleTok"
codepoint = 0            # don't reuse for other long glyphs; you can leave blank
ligature  = "underscore" # don't reuse for other long glyphs; you can leave blank
type      = "middle"
start-chaining-at       = "p i longGlyphStartTok"
end-chaining-at         = "longGlyphEndTok"
derive-glyph-from-index = 0 # wherever long pi is in the sheet
invisible-variant-name  = "invisibleLongPiMiddleTok"

[[glyphs.generated]]
name      = "longLaMiddleTok"
type      = "middle"
start-reverse-chaining-at = "closecurly l a"
end-reverse-chaining-at   = "opencurly"
invisible-variant-name    = "invisibleLongLaMiddleTok"

[settings]

# UCSUR codepoints for words not included in the default sheet, since people may write them in.
# Currently defined in cli.py, lines 114-121.
unused_ucsur_words = [
  {codepoint = 0, name = "apejaTok", ligature = "a p e j a"},
  {codepoint = 0, name = "pakeTok",  ligature = "p a k e"},
  {codepoint = 0, name = "poweTok",  ligature = "p o w e"},
]

# the following glyph names are prerequisites for custom ligatures. for example, the ligature "a l e" has "a", "l", "e" as prerequisites.
# it would be cool if they appear correctly, but if an architecture change requires it, it's fine if they appear as blank spaces.
prerequisite_glyphs = [
  # letters
  {codepoint = 0x61, name = "a", target-name = "aTok"},
  {codepoint = 0x65, name = "e", target-name = "eTok"},
  {codepoint = 0x6e, name = "n", target-name = "nTok"},
  {codepoint = 0x6f, name = "o", target-name = "oTok"},
    
  {codepoint = 0x41, name = "A", target-name = "aTok"},
  {codepoint = 0x45, name = "E", target-name = "eTok"},
  {codepoint = 0x4e, name = "N", target-name = "nTok"},
  {codepoint = 0x4f, name = "O", target-name = "oTok"},

  {codepoint = 0x49, name = "I", target-name = "i"},
  {codepoint = 0x4a, name = "J", target-name = "j"},
  {codepoint = 0x4b, name = "K", target-name = "k"},
  {codepoint = 0x4c, name = "L", target-name = "l"},
  {codepoint = 0x4d, name = "M", target-name = "m"},
  {codepoint = 0x50, name = "P", target-name = "p"},
  {codepoint = 0x53, name = "S", target-name = "s"},
  {codepoint = 0x54, name = "T", target-name = "t"},
  {codepoint = 0x55, name = "U", target-name = "u"},
  {codepoint = 0x57, name = "W", target-name = "w"},

  {codepoint = 0x62, name = "b", target-name = "p"},
  {codepoint = 0x42, name = "B", target-name = "p"},
  {codepoint = 0x63, name = "c", target-name = "s"},
  {codepoint = 0x43, name = "C", target-name = "s"},
  {codepoint = 0x64, name = "d", target-name = "t"},
  {codepoint = 0x44, name = "D", target-name = "t"},
  {codepoint = 0x66, name = "f", target-name = "p"},
  {codepoint = 0x46, name = "F", target-name = "p"},
  {codepoint = 0x67, name = "g", target-name = "k"},
  {codepoint = 0x47, name = "G", target-name = "k"},
  {codepoint = 0x68, name = "h", target-name = "k"},
  {codepoint = 0x48, name = "H", target-name = "k"},
  {codepoint = 0x71, name = "q", target-name = "k"},
  {codepoint = 0x51, name = "Q", target-name = "k"},
  {codepoint = 0x72, name = "r", target-name = "w"},
  {codepoint = 0x52, name = "R", target-name = "w"},
  {codepoint = 0x76, name = "v", target-name = "w"},
  {codepoint = 0x56, name = "V", target-name = "w"},
  {codepoint = 0x78, name = "x", target-name = "s"},
  {codepoint = 0x58, name = "X", target-name = "s"},
  {codepoint = 0x79, name = "y", target-name = "j"},
  {codepoint = 0x59, name = "Y", target-name = "j"},
  {codepoint = 0x7a, name = "z", target-name = "s"},
  {codepoint = 0x5a, name = "Z", target-name = "s"},

  # numbers (svgtottf_ffpython.py#L422-L424)

  # glyphs for punctuation used in sitelen Lasina prose, such as `,;!?` (svgtottf_ffpython.py#L440-L448)

  # glyphs for ligatures used in unsupported SP features, such as `(){}*",+&` (svgtottf_ffpython.py#L432-438)
]



# --------

# what do we need to include in the TOML to make cartouche middles *entirely* data-driven?
# such that you can implement long pi and long awen in here?
# in long pi, Start is 1000 wide and End is 0 wide.

# out of scope for now:
# in long ala, you can parse *backwards*, so there's technically *three* glyphs. is that just for ala?

# long la requires reverse chaining. when going left-to-right, you can't tell the difference between la's { and ala's {.
